In [1]:
import numpy as np

In [7]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
mask = arr>5

In [9]:
arr[mask]   #to get the all elements for which mask is true

array([ 6,  7,  8,  9, 10])

In [10]:
arr[arr%2==0]  #to get all even elements

array([ 2,  4,  6,  8, 10])

In [11]:
arr[arr<4]

array([1, 2, 3])

In [12]:
arr[arr%2==0] = 0 #we can also change value of those elements which satisifies the conditional statement
arr

array([1, 0, 3, 0, 5, 0, 7, 0, 9, 0])