In [1]:
import numpy as np

In [2]:
arr = np.array([5, 10, 15, 20, 25])
arr

array([ 5, 10, 15, 20, 25])

In [3]:
arr[0]

5

In [4]:
arr[1]

10

In [5]:
arr[45]

IndexError: index 45 is out of bounds for axis 0 with size 5

In [6]:
arr[-1]

25

In [7]:
arr[2:4]

array([15, 20])

In [8]:
arr[-1:]

array([25])

In [11]:
arr[-3:]

array([15, 20, 25])

In [12]:
arr[::-1]

array([25, 20, 15, 10,  5])

In [13]:
matrix = np.array([[10, 15, 20], [25, 30, 35], [40, 45, 50]])
matrix

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [14]:
matrix[0][1]

15

In [15]:
matrix[2][2]

50

In [16]:
matrix[2, 2]   #single bracket notation

50

In [17]:
#now slicing, let say we want to get the following subarray
# [ [10, 15],
# [25, 30] ]
matrix[0:2, :2]


array([[10, 15],
       [25, 30]])

In [20]:
# [[30, 35],
# [45, 50]]
matrix[1:, 1:]

array([[30, 35],
       [45, 50]])

In [21]:
np.random.seed(123)
matrix2 = np.random.randint(1, 101, 25).reshape(5, 5)
matrix2

array([[67, 93, 99, 18, 84],
       [58, 87, 98, 97, 48],
       [74, 33, 47, 97, 26],
       [84, 79, 37, 97, 81],
       [69, 50, 56, 68,  3]])

In [22]:
#task to get the following sub-matrix
# 87, 98, 97
# 33, 47, 97
# 79, 37, 97
matrix2[1:4, 1:4]

array([[87, 98, 97],
       [33, 47, 97],
       [79, 37, 97]])