In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])

In [3]:
arr


array([1, 2, 3, 4, 5])

In [4]:
arr2 = np.random.randint(20, 41, 10)
arr2

array([29, 35, 29, 36, 25, 29, 37, 26, 29, 34])

In [5]:
arr3 = np.ones(5)
arr3 = arr3*5
arr3

array([5., 5., 5., 5., 5.])

In [7]:
arr4 = np.hstack((arr2, arr3))
arr4

array([29., 35., 29., 36., 25., 29., 37., 26., 29., 34.,  5.,  5.,  5.,
        5.,  5.])

In [8]:
arr4 = arr4.reshape(3, -1)

In [9]:
arr4

array([[29., 35., 29., 36., 25.],
       [29., 37., 26., 29., 34.],
       [ 5.,  5.,  5.,  5.,  5.]])

In [15]:
arr5 = np.random.rand(4, 5)
arr5

array([[0.94461048, 0.8826776 , 0.99022616, 0.52033823, 0.88162358],
       [0.92278916, 0.94205868, 0.7594203 , 0.29412773, 0.35655888],
       [0.15114567, 0.59513278, 0.71305656, 0.28307406, 0.43015821],
       [0.85428293, 0.9416583 , 0.48800404, 0.78612032, 0.12843439]])

In [13]:
arr4[arr4%2==0]= -1

In [14]:
arr4

array([[29., 35., 29., -1., 25.],
       [29., 37., -1., 29., -1.],
       [ 5.,  5.,  5.,  5.,  5.]])