In [1]:
import numpy as np


In [2]:
np.random.seed(123)
matrix = np.random.randint(1, 11, 9).reshape(3, 3)

In [3]:
matrix


array([[ 3,  3,  7],
       [ 2,  4, 10],
       [ 7,  2,  1]])

In [4]:
np.sum(matrix)

39

In [5]:
matrix.sum()  #we can also do that in this way

39

In [6]:
#for row we use axis= 1 and for column wise we use axis=0
np.min(matrix, axis=1) #min element of each row in a array

array([3, 2, 1])

In [7]:
np.sum(matrix, axis=0)  #sum of each col 

array([12,  9, 18])

In [8]:
np.prod(matrix, axis=1)

array([63, 80, 14])