In [1]:
import numpy as np

In [2]:
arr = np.array([1,2 ,3,4])

In [3]:
arr*2

array([2, 4, 6, 8])

In [4]:
arr+5

array([6, 7, 8, 9])

In [5]:
arr**2

array([ 1,  4,  9, 16])

In [6]:
arr**3


array([ 1,  8, 27, 64])

In [7]:
arr = arr.reshape(2, 2)
arr

array([[1, 2],
       [3, 4]])

In [8]:
arr**2

array([[ 1,  4],
       [ 9, 16]])

In [9]:
arr/0

<ipython-input-9-39e2cbdaf753>:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0


array([[inf, inf],
       [inf, inf]])

In [14]:
arr1 = arr.reshape(1, 4)
arr2 = np.array([5, 6, 7, 8])


In [15]:
arr1+arr2

array([[ 6,  8, 10, 12]])

In [16]:
arr1/arr2

array([[0.2       , 0.33333333, 0.42857143, 0.5       ]])

In [17]:
arr1*arr2

array([[ 5, 12, 21, 32]])

In [18]:
arr1/arr1

array([[1., 1., 1., 1.]])

In [21]:
np.random.seed(123)
matrix1 = np.random.randint(1, 12, 9).reshape(3, 3)
matrix2 = np.random.randint(5, 15, 9).reshape(3, 3)
matrix1


array([[ 3,  3,  7],
       [ 2,  4, 11],
       [10,  7,  2]])

In [23]:
matrix2

array([[ 5,  6, 14],
       [ 5,  5, 14],
       [ 8,  9,  5]])

In [24]:
matrix1+matrix2

array([[ 8,  9, 21],
       [ 7,  9, 25],
       [18, 16,  7]])

In [25]:
matrix1 * matrix2   #corresponding elements will get multiplied but this is not actual matrix multiplication

array([[ 15,  18,  98],
       [ 10,  20, 154],
       [ 80,  63,  10]])

In [26]:
matrix1.dot(matrix2)  #this is actual matrix multiplication

array([[ 86,  96, 119],
       [118, 131, 139],
       [101, 113, 248]])