In [1]:
import numpy as np

In [2]:
np.random.seed(123)
arr = np.random.randint(1, 15, 15)
arr

array([14,  3, 13,  3,  7,  2,  4, 11, 12, 10,  7,  2,  1,  2, 10])

In [4]:
np.random.shuffle(arr)  #will shuffle the elements in the array
arr

array([14, 10,  3, 11,  7,  2,  2,  3, 13, 12,  2,  7,  4, 10,  1])

In [5]:
np.unique(arr)

array([ 1,  2,  3,  4,  7, 10, 11, 12, 13, 14])

In [6]:
np.unique(arr, return_index=True, return_counts=True)

(array([ 1,  2,  3,  4,  7, 10, 11, 12, 13, 14]),
 array([14,  5,  2, 12,  4,  1,  3,  9,  8,  0]),
 array([1, 3, 2, 1, 2, 2, 1, 1, 1, 1]))