In [1]:
import numpy as np

In [2]:
arr = np.array([2, 80, 1, 97, 5])

In [3]:
np.min(arr)

1

In [4]:
np.max(arr)

97

In [5]:
np.argmin(arr) #index of min number

2

In [6]:
np.argmax(arr)

3

In [7]:
np.exp(arr)   #euler value of each element

array([7.38905610e+00, 5.54062238e+34, 2.71828183e+00, 1.33833472e+42,
       1.48413159e+02])

In [8]:
np.sin(arr) #sin value of each element

array([ 0.90929743, -0.99388865,  0.84147098,  0.37960774, -0.95892427])

In [9]:
np.linspace(1, 50, 5)   #5 evenly spaced numbers b/w 1 and 50

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [10]:
arr2 = np.array([1, 2, 3, 0], dtype = 'bool')
arr2

array([ True,  True,  True, False])

In [13]:
arr2 = np.array([1, 0, 1, 1], dtype = 'bool')
arr2

array([ True, False,  True,  True])

In [17]:
for i in arr:
    print(i)

IndentationError: expected an indented block (<ipython-input-17-7c319ce25a9f>, line 2)