In [1]:
import numpy as np

In [3]:
arr = np.array([5, 10, 15, 20, 25, 30])
arr

array([ 5, 10, 15, 20, 25, 30])

In [4]:
sliced_arr = arr[2:5] #this is not copy its view
sliced_arr

array([15, 20, 25])

In [5]:
sliced_arr[:] =0
sliced_arr

array([0, 0, 0])

In [6]:
arr  #all changes can also be seen in original arr since it was'nt a copy

array([ 5, 10,  0,  0,  0, 30])

In [8]:
sliced_arr2 = arr[:2].copy()
sliced_arr2

array([ 5, 10])

In [10]:
sliced_arr2[:] =0
sliced_arr2

array([0, 0])

In [11]:
arr   #this time original arr is intact

array([ 5, 10,  0,  0,  0, 30])